sonar.organization=thaqiya
sonar.projectKey=thaqiya_Backend
sonar.sources=.
sonar.tests=.
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/__pycache__/**,**/*.pyc
